# This file enables meta-training with CUDA v11.8
# The environment additionally support data load, extract and prep.
name: meta310
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:   # Compatible with CUDA v11.8
  - python=3.10
  - numpy=1.23.5
  - pandas=2.2.3
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.56.0
  - kiwisolver=1.4.8
  - matplotlib=3.5.3
  - packaging=24.2
  - pillow=11.1.0
  - pydicom=3.0.1
  - pyparsing=3.2.3
  - python-dateutil=2.9.0.post0
  - pyyaml=6.0.2
  - six=1.17.0
  - tqdm=4.67.1
  - pytorch=2.2.0
  - torchvision=0.17.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - ultralytics
      - opencv-python
