# File: This file creates an environment that doesn't require CUDA/ GPUs.
# This environment can be used to download, extract and prep data.
# This environment does not support meta training.
name: myenv310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas==2.2.3
  - contourpy==1.3.1
  - cycler==0.12.1
  - fonttools==4.56.0
  - kiwisolver==1.4.8
  - matplotlib==3.10.1
  - numpy==2.2.4
  - packaging==24.2
  - pillow==11.1.0
  - pydicom==3.0.1
  - pyparsing==3.2.3
  - python-dateutil==2.9.0.post0
  - pyyaml==6.0.2
  - six==1.17.0
  - tqdm==4.67.1
  - opencv==4.11.0